---
# tasks file for webserver

- name: "install httpd"
  package:
    name: "httpd"
    state: present

- name: "copy the content"
  copy:
    src: "/root/Desktop/ansible_ws/ws5/webserver/files/index.php"
    dest: "/var/www/html/index.php"

- name: "restart httpd"
  service:
    name: "httpd"
    state: started

