- hosts: all

  vars:
    - dvd_dir: "/dvd1"

  tasks:

  - file:
          state: "directory"
          path: "{{ dvd_dir}}"

  - mount:
          src: "/dev/cdrom"
          path: "{{ dvd_dir }}"
          fstype: "iso9660"
          state: "mounted"

  - yum_repository:
          name: "mydvd1"
          description: "configure appstream"
          gpgcheck: no
          baseurl: "{{ dvd_dir }}/AppStream"


  - yum_repository:
          name: "mydvd2"
          description: "configure baseos"
          gpgcheck: no
          baseurl: "{{ dvd_dir }}/BaseOS"

  - package:
          name: "httpd"
          state: present

  - file:
          state: "directory"
          path: "/var/www/lw"

  - copy:
          src: "/root/Desktop/ansible_ws/ws6/lw.conf"
          dest: "/etc/httpd/conf.d/"
          

  - copy:
          content: "sadadsaadasa"
          dest: "/var/www/lw/abc.html"

  - service:
          name: "httpd"
          state: restarted
          enabled: yes

  - firewalld:
          port: "8083/tcp"
          immediate: yes
          permanent: yes
          state: "enabled"
