- hosts: all

  tasks:
  - package:
           name: "httpd"
           state: present

  - copy:
          dest: "/var/www/html/index.html"
          content: "auth added to website"

  - replace:
          path: "/etc/httpd/conf/httpd.conf"
          regexp: "AllowOverride None"
          replace: "AllowOverride AuthConfig"

  - copy:
          dest: "/var/www/html/.htaccess"
          src: ".htaccess"

          #  - package:
          #          name: "python36"

  - pip:
          name: "passlib"

  - htpasswd:
          path: "/etc/www.passwd"
          name: "sarthak"
          password: "redhat"

  - service:
          name: "httpd"
          state: restarted
